### ISSUE TITLE
Support for Amazon Linux

### ISSUE THREAD

**Issue by muram** [alertlogic/al_agents#80]
From Direct Supply (Customer):

> There seems to be explicit support for the ‘rhel’, ‘fedora’, and ‘debian’ platform families, based on how it gets the package to install for the agent, but not for ‘amazon’ which is what Amazon Linux is classified as. As such, it fails when trying to get the package to install the agent

```
========================================================================================
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/amazonlinux-base/recipes/default.rb
========================================================================================

URI::InvalidURIError
--------------------
bad URI(is not URI?):

Cookbook Trace:
---------------
  /tmp/kitchen/cache/cookbooks/al_agents/libraries/helpers.rb:14:in `agent_file'
  /tmp/kitchen/cache/cookbooks/al_agents/libraries/helpers.rb:18:in `agent_basename'
  /tmp/kitchen/cache/cookbooks/al_agents/recipes/install.rb:11:in `from_file'
  /tmp/kitchen/cache/cookbooks/al_agents/recipes/_linux.rb:7:in `from_file'
  /tmp/kitchen/cache/cookbooks/al_agents/recipes/default.rb:11:in `from_file'
  /tmp/kitchen/cache/cookbooks/amazonlinux-base/recipes/default.rb:120:in `from_file'

Relevant File Content:
----------------------
/tmp/kitchen/cache/cookbooks/al_agents/libraries/helpers.rb:

  7:      def al_agent
  8:        node['al_agents']['package']['name']
  9:      end
 10:
 11:      def agent_file(uri)
 12:        require 'pathname'
 13:        require 'uri'
 14>>       Pathname.new(URI.parse(uri).path).basename.to_s
 15:      end
 16:
 17:      def agent_basename
 18:        agent_file(node['al_agents']['package']['url'])
 19:      end
 20:
 21:      def al_agent_service
 22:        node['al_agents']['agent']['al_agent_service']
 23:      end
```

**Comment by jstrassburg** [comment]
Additional info: https://docs.chef.io/deprecations_ohai_amazon_linux.html

**Comment by fss18** [comment]
this issue fixed on https://github.com/alertlogic/al_agents/pull/82
